name: Scrape Clothes

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: yarn
        working-directory: ./
        run: |
          yarn --no-package-lock

      - name: install playwright
        working-directory: ./
        run: |
          npx playwright install chromium

      - name: scrape clothes
        working-directory: ./
        run: |
          node listings-scraper/scripts/runner.js

      - name: Check for changes
        id: check_changes
        run: |
          changes=$(git status --porcelain)
          if [ -n "$changes" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug
          path: |
            ./screenshot_*.png
            ./debug_page_*.html


      - name: commit changes if any
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m 'github-bot: scrape clothes'
          git push
